name: Pull Request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '*.md'

jobs:
  tests:
    name: Test (SwiftPM)
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.4
    with:
      linux_swift_versions: '["nightly-main"]'
      windows_swift_versions: '["nightly-main"]'
      # enable_macos_checks: false
      # macos_xcode_versions: '["26.2"]'
      # macos_versions: '["tahoe"]'
      # enable_wasm_sdk_build: true
      # wasm_sdk_versions: '["nightly-main"]'
      # enable_android_sdk_build: true
      # android_sdk_versions: '["nightly-main"]'

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@0.0.4
    with:
      license_header_check_project_name: "Swift.org"
      license_header_check_enabled: false
      docs_check_enabled: false
      format_check_enabled: true
      unacceptable_language_check_enabled: true
      api_breakage_check_enabled: false